const MIN_AMOUNT = 10;
const MIN_TOLERANCE = 9;
const MIN_BNB_BALANCE = 0.001;
const MIN_ETH_BALANCE = 0.0001;
const MIN_ETH_TOPUP = 0.000007;

module.exports = {MIN_AMOUNT,MIN_TOLERANCE,MIN_BNB_BALANCE,MIN_ETH_BALANCE,MIN_ETH_TOPUP}